services:
  mysql:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 
      MYSQL_DATABASE: 
      MYSQL_USER:
      MYSQL_PASSWORD:  
    volumes:
      - ./mysql:/var/lib/mysql
    ports:
      - "3310:3306" 

networks:
  app-network:
    driver: bridge